services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER : ${POSTGRES_USER}
      POSTGRES_PASSWORD  : ${POSTGRES_PASSWORD}
      POSTGRES_DB : ${POSTGRES_DB}
    
    ports:
      - "5432:5432"

    expose:
      - 5432
    
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    
    networks:
      - teste_anka_tech
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - 5672
    networks:
      - teste_anka_tech
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "check_running"]
      interval: 5s
      timeout: 3s
      retries: 5
    
  backend:
    build:
      context: ./backend
      dockerfile: app.dockerfile
    depends_on: 
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    volumes:
    - ./backend/reports:/backend/reports
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - RABBITMQ_URL=${RABBITMQ_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEBUG=${DEBUG}
      - PORT=${PORT}
      - RABBIT_QUEUE=${RABBIT_QUEUE}
    ports:
      - 5000:5000
    networks:
      - teste_anka_tech


networks:
  teste_anka_tech:
    driver: bridge